from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
            options={"verbose_name": "تصنيف مقال", "verbose_name_plural": "تصنيفات المقالات", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
            options={"verbose_name": "وسم", "verbose_name_plural": "الوسوم", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("short_description", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_generate_service_pages", models.BooleanField(default=True)),
            ],
            options={"verbose_name": "مدينة", "verbose_name_plural": "المدن", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("city_name", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("new", "جديد"), ("contacted", "تم التواصل"), ("closed", "مغلق")], default="new", max_length=20)),
                ("notes", models.TextField(blank=True)),
            ],
            options={"verbose_name": "طلب عميل", "verbose_name_plural": "طلبات العملاء", "ordering": ["status", "-created_at"]},
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="core.mediafolder")),
            ],
            options={"verbose_name": "مجلد وسائط", "verbose_name_plural": "مجلدات الوسائط", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("menu_title", models.CharField(blank=True, max_length=120)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("intro_text", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("template_key", models.CharField(choices=[("home", "الرئيسية"), ("about", "من نحن"), ("services", "الخدمات"), ("portfolio", "الأعمال"), ("cities", "المدن"), ("blog", "المدونة"), ("contact", "اتصل بنا"), ("custom", "صفحة مخصصة")], default="custom", max_length=30)),
                ("custom_url", models.CharField(blank=True, help_text="مثال: offers أو about-us", max_length=180)),
                ("is_visible", models.BooleanField(default=True)),
                ("show_in_menu", models.BooleanField(default=True)),
                ("menu_order", models.PositiveIntegerField(default=0)),
            ],
            options={"verbose_name": "صفحة", "verbose_name_plural": "الصفحات", "ordering": ["menu_order", "title"]},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("short_title", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField()),
                ("benefits", models.TextField(blank=True, help_text="أدخل ميزة في كل سطر")),
                ("image", models.ImageField(blank=True, null=True, upload_to="services/")),
                ("image_url", models.URLField(blank=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("cities", models.ManyToManyField(blank=True, related_name="services", to="core.city")),
            ],
            options={"verbose_name": "خدمة", "verbose_name_plural": "الخدمات", "ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("city_name", models.CharField(blank=True, max_length=120)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review", models.TextField()),
                ("is_visible", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"verbose_name": "تقييم عميل", "verbose_name_plural": "تقييمات العملاء", "ordering": ["display_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("category", models.CharField(choices=[("shades", "مظلات"), ("fencing", "شبوك"), ("palm", "نخيل"), ("traditional", "مباني تراثية")], max_length=30)),
                ("description", models.TextField()),
                ("featured_image", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("featured_image_url", models.URLField(blank=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("city", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projects", to="core.city")),
            ],
            options={"verbose_name": "مشروع", "verbose_name_plural": "المشاريع", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("featured_image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("featured_image_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posts", to="core.blogcategory")),
                ("tags", models.ManyToManyField(blank=True, related_name="posts", to="core.blogtag")),
            ],
            options={"verbose_name": "مقال", "verbose_name_plural": "المقالات", "ordering": ["-publish_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="CityServicePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("benefits", models.TextField(blank=True, help_text="أدخل ميزة في كل سطر")),
                ("is_active", models.BooleanField(default=True)),
                ("custom_slug", models.SlugField(blank=True, max_length=160)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="city_services", to="core.city")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="city_pages", to="core.service")),
            ],
            options={"verbose_name": "خدمة داخل مدينة", "verbose_name_plural": "الخدمات داخل المدن", "ordering": ["city__name", "service__title"], "unique_together": {("city", "service")}},
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                ("route_name", models.CharField(blank=True, help_text="مثل home أو contact", max_length=80)),
                ("external_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("linked_page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="nav_items", to="core.page")),
            ],
            options={"verbose_name": "عنصر قائمة", "verbose_name_plural": "عناصر القائمة", "ordering": ["sort_order", "label"]},
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("image_type", models.CharField(choices=[("before", "قبل"), ("after", "بعد"), ("gallery", "معرض")], default="gallery", max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="projects/gallery/")),
                ("external_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery", to="core.project")),
            ],
            options={"verbose_name": "صورة مشروع", "verbose_name_plural": "صور المشاريع", "ordering": ["sort_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="pagemedia",
            name="folder",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="images", to="core.mediafolder"),
        ),
        migrations.AddField(model_name="sitesettings", name="address", field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name="sitesettings", name="email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name="sitesettings", name="facebook_url", field=models.URLField(blank=True)),
        migrations.AddField(model_name="sitesettings", name="instagram_url", field=models.URLField(blank=True)),
        migrations.AddField(model_name="sitesettings", name="linkedin_url", field=models.URLField(blank=True)),
        migrations.AddField(model_name="sitesettings", name="x_url", field=models.URLField(blank=True)),
    ]
