# Generated by Django 4.2.7 on 2026-03-22 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
