# Generated by Django 4.2.7 on 2026-03-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_libraryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
    ]
