# Generated by Django 5.1.5 on 2026-04-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_blogpost_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContentGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('blog_post', 'مقال'), ('service', 'خدمة'), ('city', 'مدينة'), ('page', 'صفحة'), ('city_service', 'خدمة داخل مدينة')], max_length=30)),
                ('mode', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث')], default='create', max_length=20)),
                ('prompt', models.TextField()),
                ('title_hint', models.CharField(blank=True, max_length=255)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('generated_payload', models.JSONField(blank=True, default=dict)),
                ('target_object_type', models.CharField(blank=True, max_length=100)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_content_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل إنشاء محتوى بالذكاء الاصطناعي',
                'verbose_name_plural': 'سجلات إنشاء المحتوى بالذكاء الاصطناعي',
                'ordering': ['-created_at'],
            },
        ),
    ]
