# Generated by Django 5.1.5 on 2026-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aicontentgenerationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryimage',
            name='category',
            field=models.CharField(choices=[('shades', 'تصميم حدائق'), ('fencing', 'لاندسكيب صلب'), ('palm', 'أشجار ونخيل'), ('traditional', 'أنظمة ري وصيانة'), ('general', 'عام')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('shades', 'تصميم حدائق'), ('fencing', 'لاندسكيب صلب'), ('palm', 'أشجار ونخيل'), ('traditional', 'أنظمة ري وصيانة')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_meta_description',
            field=models.TextField(default='شركة سعودية متخصصة في تصميم الحدائق وتنفيذ اللاندسكيب وزراعة الأشجار والنخيل وأنظمة الري في جميع مدن المملكة.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_meta_title',
            field=models.CharField(default='لاندسكيب وتنسيق حدائق وأشجار ونخيل في السعودية', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='نخيل نجد', max_length=200),
        ),
    ]
