# Generated by Django 5.1.5 on 2026-04-15 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_libraryimage_category_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_og_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_description',
            field=models.TextField(blank=True, default='شركة متخصصة في خدمات اللاندسكيب وتنسيق الحدائق والأشجار والنخيل والمظلات والشبوك في السعودية.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_keywords',
            field=models.CharField(blank=True, default='لاندسكيب, تصميم حدائق, تنسيق حدائق, أشجار, نخيل, مظلات, شبوك, السعودية', help_text='كلمات مفتاحية افتراضية مفصولة بفواصل.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_twitter_handle',
            field=models.CharField(blank=True, help_text='مثال: @yourbrand', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_highlights',
            field=models.TextField(default='تصميم حدائق\nلاندسكيب\nأشجار ونخيل\nشبوك\nمظلات', help_text='أدخل خدمة في كل سطر لتظهر في محتوى الموقع وتهيئة SEO.'),
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='رقم التواصل', max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('enable_whatsapp', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'رقم تواصل',
                'verbose_name_plural': 'أرقام التواصل',
                'ordering': ['-is_primary', 'sort_order', 'id'],
            },
        ),
    ]
