# Generated by Django 5.2.13 on 2026-05-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_default_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(help_text='مثال: /riyadh/shades/', max_length=255, unique=True)),
                ('target_path', models.CharField(help_text='مثال: /riyadh/landscaping/', max_length=255)),
                ('is_permanent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'تحويل رابط قديم',
                'verbose_name_plural': 'تحويلات الروابط القديمة',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='SEOReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('issue_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('high', 'مرتفع'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('fixed', 'تم الإصلاح'), ('ignored', 'متجاهل')], default='open', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشكلة SEO',
                'verbose_name_plural': 'تقرير SEO اليومي',
                'ordering': ['status', '-severity', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google Search Console'), ('bing', 'Bing Webmaster Tools'), ('yandex', 'Yandex'), ('custom', 'كود مخصص')], default='google', max_length=30)),
                ('name', models.CharField(default='google-site-verification', max_length=120)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('raw_html', models.TextField(blank=True, help_text='استخدمه فقط لكود meta كامل موثوق.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'كود تحقق',
                'verbose_name_plural': 'أكواد التحقق',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_country',
            field=models.CharField(default='SA', max_length=2),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_locality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='area_served',
            field=models.TextField(blank=True, help_text='سطر لكل مدينة أو منطقة خدمة'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_type',
            field=models.CharField(default='LocalBusiness', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_property',
            field=models.URLField(blank=True, help_text='مثال: https://example.com/ أو sc-domain:example.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_service_account_json',
            field=models.TextField(blank=True, help_text='JSON لحساب الخدمة الخاص بـ Google Search Console. احفظه فقط في بيئة موثوقة.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='سطر لكل يوم بصيغة schema.org مثل Mo-Sa 08:00-20:00'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='same_as_links',
            field=models.TextField(blank=True, help_text='سطر لكل رابط اجتماعي أو ملف تعريفي خارجي'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(blank=True, help_text='مثال: Google Business Profile أو عميل مباشر', max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SearchConsoleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=500)),
                ('page', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('device', models.CharField(blank=True, max_length=30)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'كلمة من Search Console',
                'verbose_name_plural': 'كلمات Search Console',
                'ordering': ['-impressions', 'position'],
                'indexes': [models.Index(fields=['query', 'page'], name='core_search_query_34b714_idx')],
            },
        ),
    ]
