# Generated by Django 5.2.13 on 2026-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_legacyredirect_seoreportissue_siteverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'قيد التشغيل'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('skipped', 'متجاوز')], default='running', max_length=20)),
                ('search_console_result', models.JSONField(blank=True, default=dict)),
                ('local_seo_result', models.JSONField(blank=True, default=dict)),
                ('redirects_result', models.JSONField(blank=True, default=dict)),
                ('issues_before', models.PositiveIntegerField(default=0)),
                ('issues_after', models.PositiveIntegerField(default=0)),
                ('ai_requested', models.BooleanField(default=False)),
                ('ai_applied', models.BooleanField(default=False)),
                ('ai_result', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'تشغيل أتمتة SEO',
                'verbose_name_plural': 'تشغيلات أتمتة SEO',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_seo_auto_apply',
            field=models.BooleanField(default=False, help_text='تطبيق تعديلات الذكاء الاصطناعي تلقائيًا عند تشغيل أمر الأتمتة.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_seo_enabled',
            field=models.BooleanField(default=True, help_text='تشغيل منظومة تحسين SEO اليومية.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_seo_research_queries',
            field=models.TextField(blank=True, help_text='استعلامات بحث إضافية، سطر لكل استعلام. تستخدمها الأتمتة اليومية مع Search Console.'),
        ),
    ]
