# Generated by Django 5.2.13 on 2026-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seoautomationrun_sitesettings_ai_seo_auto_apply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('whatsapp', 'واتساب'), ('call', 'اتصال'), ('calculator', 'حاسبة تكلفة'), ('exit_intent', 'نافذة خروج')], max_length=30)),
                ('page_url', models.URLField(blank=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'حدث تحويل',
                'verbose_name_plural': 'تتبع التحويلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
