# Generated by Django 5.2.13 on 2026-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_conversionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryimage',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='libraryimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryimage',
            name='image_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
