# Generated by Django 5.2.13 on 2026-05-02 17:14

from django.db import migrations, models


def mark_existing_database_images(apps, schema_editor):
    LibraryImage = apps.get_model("core", "LibraryImage")
    LibraryImage.objects.exclude(image_data__isnull=True).update(image_stored=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_libraryimage_image_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryimage',
            name='image_stored',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(mark_existing_database_images, migrations.RunPython.noop),
    ]
