# Generated by Django 5.2.16 on 2026-08-04 04:44

import django.core.validators
import core.models
from django.db import migrations, models


def seed_identity_defaults(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    settings_obj = SiteSettings.objects.filter(pk=1).first()
    if not settings_obj:
        return
    changed_fields = []
    if not settings_obj.homepage_hero_mobile_background_url:
        settings_obj.homepage_hero_mobile_background_url = "/static/hero-mobile.webp"
        changed_fields.append("homepage_hero_mobile_background_url")
    if not settings_obj.homepage_hero_alt:
        settings_obj.homepage_hero_alt = "نخيل ولاندسكيب في مساحة خارجية من تنفيذ نخيل نجد"
        changed_fields.append("homepage_hero_alt")
    if changed_fields:
        settings_obj.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cityservicepage_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_alt',
            field=models.CharField(blank=True, help_text='وصف مختصر ودقيق للصورة لتحسين الوصول وSEO الصور.', max_length=180, verbose_name='وصف صورة الهيرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تركيز الهيرو أفقيًا (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_focus_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تركيز الهيرو رأسيًا (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_mobile_background',
            field=models.ImageField(blank=True, help_text='صورة عمودية اختيارية للهاتف. عند تركها فارغة تُستخدم صورة الهيرو الرئيسية.', null=True, upload_to='site-settings/branding/', verbose_name='صورة هيرو الهاتف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_mobile_background_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط صورة هيرو الهاتف'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_hero_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=62, help_text='قيمة بين 20 و90 لضمان وضوح النص فوق الصورة.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(90)], verbose_name='قوة تعتيم الهيرو (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site-settings/branding/', verbose_name='شعار الموقع'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_alt',
            field=models.CharField(blank=True, help_text='يُستخدم اسم الموقع تلقائيًا عند تركه فارغًا.', max_length=160, verbose_name='وصف الشعار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_hero_background_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='blog_hero_background_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_og_image_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source]),
        ),
        migrations.RunPython(seed_identity_defaults, migrations.RunPython.noop),
    ]
