# Generated by Django 5.2.17 on 2026-08-09 01:32

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_homepage_cms(apps, schema_editor):
    HomeSection = apps.get_model("core", "HomeSection")
    HomeSectionMedia = apps.get_model("core", "HomeSectionMedia")
    SiteSettings = apps.get_model("core", "SiteSettings")
    site, _ = SiteSettings.objects.get_or_create(pk=1)
    changed_fields = []
    if not site.homepage_meta_title or site.homepage_meta_title == "لاندسكيب وتنسيق حدائق وأشجار ونخيل في السعودية":
        site.homepage_meta_title = "تنسيق حدائق ولاندسكيب وزراعة نخيل في السعودية | نخيل نجد"
        changed_fields.append("homepage_meta_title")
    if not site.homepage_meta_description or site.homepage_meta_description == "شركة سعودية متخصصة في تصميم الحدائق وتنفيذ اللاندسكيب وزراعة الأشجار والنخيل وأنظمة الري في جميع مدن المملكة.":
        site.homepage_meta_description = "تصميم وتنفيذ تنسيق الحدائق واللاندسكيب وزراعة ونقل النخيل وشبكات الري وصيانة المساحات الخارجية في مدن السعودية بخطة واضحة تناسب الموقع والمناخ."
        changed_fields.append("homepage_meta_description")
    if not site.seo_default_keywords or site.seo_default_keywords == "لاندسكيب, تصميم حدائق, تنسيق حدائق, أشجار, نخيل, مظلات, شبوك, السعودية":
        site.seo_default_keywords = "تنسيق حدائق, شركة تنسيق حدائق, لاندسكيب, تصميم حدائق منزلية, زراعة نخيل, نقل نخيل, شبكات ري, صيانة حدائق, السعودية"
        changed_fields.append("seo_default_keywords")
    if not site.ai_seo_research_queries:
        site.ai_seo_research_queries = "تنسيق حدائق الرياض\nشركة تنسيق حدائق بالرياض\nلاندسكيب الرياض\nتصميم حدائق منزلية\nزراعة ونقل نخيل\nشبكات ري أوتوماتيكية\nصيانة حدائق\nتنسيق حدائق جدة\nتنسيق حدائق الدمام"
        changed_fields.append("ai_seo_research_queries")
    if changed_fields:
        site.save(update_fields=changed_fields)
    section_defaults = [
        {
            "key": "hero", "sort_order": 10, "theme": "media", "eyebrow": "نخيل نجد",
            "kicker": "تنسيق حدائق · لاندسكيب · نخيل · شبكات ري",
            "title": "تنسيق حدائق\nولاندسكيب\nيصنع الفرق.",
            "description": "نصمم وننفذ المساحات الخارجية في السعودية؛ من اختيار النخيل والنباتات إلى شبكات الري والتشطيبات والعناية بعد التنفيذ.",
            "primary_cta_label": "اطلب معاينة", "primary_cta_url": "/contact/",
            "secondary_cta_label": "شاهد الأعمال", "secondary_cta_url": "/projects/",
            "video_url": "/videos/hero-triptych.mp4", "mobile_video_url": "/videos/hero-mobile.mp4",
            "poster_url": "/video-posters/hero-triptych.webp", "media_alt": "تنسيق حدائق وزراعة نخيل في مشروع لاندسكيب", "overlay_opacity": 62,
        },
        {
            "key": "manifesto", "sort_order": 20, "theme": "dark", "eyebrow": "من نحن",
            "title": "النخلة مو تفصيل.\nهي توقيع المكان.",
            "description": "نقرأ الموقع قبل ما نرسمه، ونختار عناصر تتحمل المناخ وتخدم الاستخدام وتبقى جميلة مع الوقت.",
            "primary_cta_label": "اكتشف قصتنا", "primary_cta_url": "/about/",
        },
        {
            "key": "stories", "sort_order": 30, "theme": "paper", "eyebrow": "قصص من الميدان",
            "title": "التنفيذ\nيتكلم.",
            "description": "لقطات حقيقية توضّح دقة نقل النخيل والزراعة والعناية بالمشهد بعد اكتماله.",
        },
        {
            "key": "gallery", "sort_order": 40, "theme": "paper", "eyebrow": "تفاصيل من أعمالنا",
            "title": "من الزراعة\nإلى المشهد المكتمل.",
            "description": "تكوين نباتي، مسطحات خضراء، إنارة وعناصر مائية مصممة كجزء واحد من المساحة.",
        },
        {
            "key": "services", "sort_order": 50, "theme": "dark", "eyebrow": "خدماتنا",
            "title": "خبرة تبدأ\nمن الأرض.",
            "description": "تنسيق حدائق ولاندسكيب وزراعة نخيل وشبكات ري وصيانة، بنطاق واضح يناسب الموقع والميزانية.",
            "primary_cta_label": "جميع الخدمات", "primary_cta_url": "/services/",
        },
        {
            "key": "process", "sort_order": 60, "theme": "paper", "eyebrow": "منهج التنفيذ",
            "title": "من المعاينة\nإلى مشهد مكتمل.",
            "description": "رحلة واضحة تقلل المفاجآت وتربط التصميم بالتكلفة والتنفيذ والعناية اللاحقة.",
            "primary_cta_label": "ابدأ مشروعك", "primary_cta_url": "/quote-request/",
        },
        {
            "key": "feature", "sort_order": 70, "theme": "media", "eyebrow": "مشهد مختار",
            "title": "مشروع يختصر\nجودة التنفيذ.",
            "primary_cta_label": "تفاصيل العمل",
        },
        {
            "key": "coverage", "sort_order": 80, "theme": "paper", "eyebrow": "نطاق التغطية",
            "title": "معرفة محلية.\nعلى امتداد المملكة.",
            "description": "صفحات واضحة لكل مدينة وحي تساعدك تعرف الخدمة الأقرب وتفاصيلها قبل طلب المعاينة.",
            "primary_cta_label": "استكشف المدن", "primary_cta_url": "/cities/",
        },
        {
            "key": "projects", "sort_order": 90, "theme": "dark", "eyebrow": "معرض الأعمال",
            "title": "تفاصيل تشوفها\nقبل ما تختار.",
            "primary_cta_label": "كامل المعرض", "primary_cta_url": "/projects/",
        },
        {
            "key": "testimonials", "sort_order": 100, "theme": "paper", "eyebrow": "تجارب العملاء",
            "title": "ثقة تُبنى\nفي التفاصيل.",
            "description": "آراء موثقة من عملاء اختبروا وضوح التواصل وجودة التنفيذ والمتابعة.",
        },
        {
            "key": "insights", "sort_order": 110, "theme": "paper", "eyebrow": "دليل الخبرة",
            "title": "معرفة تسبق التنفيذ.",
            "description": "أدلة عملية عن تنسيق الحدائق واختيار النخيل وشبكات الري والصيانة في مناخ السعودية.",
            "primary_cta_label": "كل المقالات", "primary_cta_url": "/blog/",
        },
        {
            "key": "faq", "sort_order": 120, "theme": "dark", "eyebrow": "أسئلة قبل البداية",
            "title": "قرارات أوضح\nلمشروع أفضل.",
            "description": "إجابات مختصرة على أكثر الأسئلة اللي تتكرر قبل تصميم وتنفيذ الحديقة.",
        },
        {
            "key": "closing", "sort_order": 130, "theme": "media", "eyebrow": "ابدأ مشروعك",
            "title": "خلّ المكان\nيتكلم عنك.",
            "description": "أرسل موقع المشروع واحتياجك، ونرتب معك المعاينة والخطوة الأنسب بوضوح.",
            "primary_cta_label": "اطلب عرض سعر", "primary_cta_url": "/quote-request/",
            "secondary_cta_label": "تواصل معنا", "secondary_cta_url": "/contact/",
            "video_url": "/videos/story-finished.mp4", "poster_url": "/video-posters/story-finished.webp",
            "media_alt": "حديقة نخيل مكتملة بعد تنفيذ اللاندسكيب", "overlay_opacity": 72,
        },
        {
            "key": "marquee", "sort_order": 140, "theme": "dark", "eyebrow": "خدمات نخيل نجد",
            "supporting_text": "تنسيق حدائق\nلاندسكيب\nزراعة ونقل نخيل\nشبكات ري\nصيانة حدائق\nمسطحات خضراء",
        },
    ]
    sections = {}
    for defaults in section_defaults:
        key = defaults.pop("key")
        sections[key], _ = HomeSection.objects.update_or_create(key=key, defaults=defaults)

    media_defaults = [
        ("stories", "video", "01 · بعد التنفيذ", "نخيل يصنع إيقاع المكان", "", "", "/videos/story-night.mp4", "/video-posters/story-night.webp", 10),
        ("stories", "video", "02 · نقل وزراعة", "تنفيذ محسوب من الرفع إلى التثبيت", "", "", "/videos/story-transplant.mp4", "/video-posters/story-transplant.webp", 20),
        ("stories", "video", "03 · العناية", "تفاصيل تحافظ على الأثر", "", "", "/videos/story-care.mp4", "/video-posters/story-care.webp", 30),
        ("gallery", "image", "01", "نخيل ومداخل", "", "/editorial/gardens/palm-entry.webp", "", "", 10),
        ("gallery", "image", "02", "مسطحات خضراء", "", "/editorial/gardens/lawn-park.webp", "", "", 20),
        ("gallery", "image", "03", "تكوين نباتي", "", "/editorial/gardens/palm-lawn.webp", "", "", 30),
        ("gallery", "image", "04", "إنارة خارجية", "", "/editorial/gardens/garden-lighting.webp", "", "", 40),
        ("gallery", "image", "05", "حدائق وعناصر مائية", "", "/editorial/gardens/garden-water.webp", "", "", 50),
        ("gallery", "image", "06", "اختيار من المشتل", "", "/editorial/gardens/palm-nursery.webp", "", "", 60),
        ("process", "text", "01", "معاينة وقراءة الموقع", "نفهم المساحة والاستخدام والتربة والشمس ومصدر المياه قبل اقتراح أي حل.", "", "", "", 10),
        ("process", "text", "02", "تصور ونطاق واضح", "نحدد التكوين النباتي والخامات وشبكة الري ومراحل التنفيذ بما يناسب الأولويات.", "", "", "", 20),
        ("process", "text", "03", "تنفيذ منظم", "ننسق الأعمال المدنية والزراعة والري والإنارة مع متابعة التفاصيل في الموقع.", "", "", "", 30),
        ("process", "text", "04", "تسليم وعناية", "نسلم المشهد مع إرشادات تشغيل الري والعناية وخيارات الصيانة الدورية.", "", "", "", 40),
        ("faq", "text", "", "كم تكلفة تنسيق حديقة منزلية؟", "تختلف حسب المساحة وحالة الموقع ونوع النباتات والخامات وشبكة الري. المعاينة وتحديد النطاق تعطي تقديرًا أدق من سعر عام.", "", "", "", 10),
        ("faq", "text", "", "وش يشمل تصميم وتنفيذ اللاندسكيب؟", "يشمل تخطيط المساحة، اختيار النباتات والنخيل، الممرات والمسطحات الخضراء، الري والإنارة والعناصر الجمالية حسب نطاق المشروع.", "", "", "", 20),
        ("faq", "text", "", "هل توفرون نقل وزراعة النخيل؟", "نعم، يتم تقييم حجم النخلة وحالتها ومسار الرفع وموقع الزراعة وتجهيز الحفرة والتثبيت والري قبل تنفيذ النقل.", "", "", "", 30),
        ("faq", "text", "", "كيف تختارون النباتات المناسبة لمناخ السعودية؟", "نوازن بين تحمل الحرارة واحتياج المياه وطبيعة التربة والتعرض للشمس وحجم النبات بعد النمو، مو بس شكله وقت الزراعة.", "", "", "", 40),
        ("faq", "text", "", "هل تشمل الخدمة شبكات الري وصيانة الحدائق؟", "تتوفر شبكات ري أوتوماتيكية وخطط تشغيل وصيانة دورية حسب احتياج المشروع والمدينة ونوع الزراعة.", "", "", "", 50),
    ]
    for section_key, media_type, label, title, description, image_url, video_url, poster_url, sort_order in media_defaults:
        HomeSectionMedia.objects.create(
            section=sections[section_key], media_type=media_type, label=label, title=title,
            description=description, alt_text=title, image_url=image_url, video_url=video_url,
            poster_url=poster_url, sort_order=sort_order, is_active=True,
        )


def unseed_homepage_cms(apps, schema_editor):
    HomeSection = apps.get_model("core", "HomeSection")
    HomeSection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_local_image_source_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('hero', 'الهيرو الرئيسي'), ('manifesto', 'الرؤية والتعريف'), ('stories', 'قصص من الميدان'), ('gallery', 'معرض الصور'), ('services', 'الخدمات'), ('process', 'منهج التنفيذ'), ('feature', 'المشروع المميز'), ('coverage', 'نطاق التغطية'), ('projects', 'معرض الأعمال'), ('testimonials', 'آراء العملاء'), ('insights', 'المقالات'), ('faq', 'الأسئلة الشائعة'), ('closing', 'دعوة التواصل الختامية'), ('marquee', 'الشريط المتحرك')], max_length=30, unique=True, verbose_name='القسم')),
                ('eyebrow', models.CharField(blank=True, max_length=140, verbose_name='العنوان الصغير')),
                ('kicker', models.CharField(blank=True, max_length=180, verbose_name='السطر التعريفي')),
                ('title', models.TextField(blank=True, help_text='يمكن وضع كل جزء من العنوان في سطر مستقل.', verbose_name='العنوان الرئيسي')),
                ('description', models.TextField(blank=True, verbose_name='النص الوصفي')),
                ('supporting_text', models.TextField(blank=True, verbose_name='نص إضافي')),
                ('primary_cta_label', models.CharField(blank=True, max_length=80, verbose_name='نص الزر الرئيسي')),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_link_target], verbose_name='رابط الزر الرئيسي')),
                ('secondary_cta_label', models.CharField(blank=True, max_length=80, verbose_name='نص الزر الثاني')),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_link_target], verbose_name='رابط الزر الثاني')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-sections/images/', verbose_name='صورة القسم')),
                ('image_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط صورة القسم')),
                ('video', models.FileField(blank=True, null=True, storage=core.models.home_video_storage, upload_to='home-sections/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), core.models.validate_home_video_size], verbose_name='فيديو القسم')),
                ('video_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_video_source], verbose_name='رابط فيديو القسم')),
                ('mobile_video', models.FileField(blank=True, null=True, storage=core.models.home_video_storage, upload_to='home-sections/videos/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), core.models.validate_home_video_size], verbose_name='فيديو الجوال')),
                ('mobile_video_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_video_source], verbose_name='رابط فيديو الجوال')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='home-sections/posters/', verbose_name='صورة انتظار الفيديو')),
                ('poster_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط صورة انتظار الفيديو')),
                ('media_alt', models.CharField(blank=True, max_length=220, verbose_name='وصف الصورة أو الفيديو')),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=62, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(95)], verbose_name='تعتيم الوسائط (%)')),
                ('theme', models.CharField(choices=[('dark', 'داكن'), ('paper', 'فاتح'), ('media', 'صورة أو فيديو كامل')], default='paper', max_length=12, verbose_name='نمط القسم')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب القسم')),
                ('is_visible', models.BooleanField(default=True, verbose_name='إظهار القسم')),
            ],
            options={
                'verbose_name': 'قسم ثابت في الرئيسية',
                'verbose_name_plural': 'أقسام الصفحة الرئيسية',
                'ordering': ['sort_order', 'key'],
                'indexes': [models.Index(fields=['is_visible', 'sort_order'], name='home_section_visible_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('text', 'نص أو خطوة'), ('image', 'صورة'), ('video', 'فيديو')], default='text', max_length=10, verbose_name='نوع العنصر')),
                ('label', models.CharField(blank=True, max_length=140, verbose_name='التصنيف أو الرقم')),
                ('title', models.CharField(max_length=240, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='الوصف البديل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-sections/items/images/', verbose_name='الصورة')),
                ('image_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط الصورة')),
                ('video', models.FileField(blank=True, null=True, storage=core.models.home_video_storage, upload_to='home-sections/items/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), core.models.validate_home_video_size], verbose_name='الفيديو')),
                ('video_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_video_source], verbose_name='رابط الفيديو')),
                ('mobile_video', models.FileField(blank=True, null=True, storage=core.models.home_video_storage, upload_to='home-sections/items/videos/mobile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), core.models.validate_home_video_size], verbose_name='فيديو الجوال')),
                ('mobile_video_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_video_source], verbose_name='رابط فيديو الجوال')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='home-sections/items/posters/', verbose_name='صورة انتظار الفيديو')),
                ('poster_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_image_source], verbose_name='رابط صورة انتظار الفيديو')),
                ('link_label', models.CharField(blank=True, max_length=80, verbose_name='نص الرابط')),
                ('link_url', models.CharField(blank=True, max_length=500, validators=[core.models.validate_link_target], verbose_name='الرابط')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='إظهار العنصر')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.homesection', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'عنصر داخل قسم رئيسي',
                'verbose_name_plural': 'عناصر أقسام الرئيسية',
                'ordering': ['section__sort_order', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['section', 'is_active', 'sort_order'], name='home_media_active_idx')],
            },
        ),
        migrations.RunPython(seed_homepage_cms, unseed_homepage_cms),
    ]
