import type { Metadata } from "next";
import Link from "next/link";

import { ArticleCard } from "@/components/content/Cards";
import { ArticleContent } from "@/components/content/ArticleContent";
import { ResponsiveImage } from "@/components/content/ResponsiveImage";
import { CallToAction } from "@/components/content/CallToAction";
import { JsonLd } from "@/components/seo/JsonLd";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { Container } from "@/components/ui/Container";
import { PageHero } from "@/components/ui/PageHero";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { buildMetadata, SITE_URL } from "@/lib/metadata";
import { detailApi } from "@/lib/page-data";
import type { Article } from "@/types";

async function getArticle(slug: string) { return detailApi<Article>(`blog/${encodeURIComponent(slug)}/`, 300, ["articles", `article-${slug}`]); }
export async function generateMetadata({ params }: { params: Promise<{ postSlug: string }> }): Promise<Metadata> { const { postSlug } = await params; return buildMetadata((await getArticle(postSlug)).seo); }
export default async function ArticlePage({ params }: { params: Promise<{ postSlug: string }> }) { const { postSlug } = await params; const article = await getArticle(postSlug); const date = article.published_at || article.created_at; const articleUrl = `${SITE_URL}${article.url}`; const shareText = encodeURIComponent(article.title); const shareUrl = encodeURIComponent(articleUrl); const schema = { "@context": "https://schema.org", "@type": "BlogPosting", headline: article.title, description: article.excerpt, image: article.image?.url, datePublished: date, dateModified: article.updated_at, mainEntityOfPage: articleUrl, author: { "@type": "Organization", name: "نخيل نجد", url: SITE_URL }, publisher: { "@type": "Organization", name: "نخيل نجد", url: SITE_URL } }; return <><PageHero eyebrow={article.category?.name || "مقال"} title={article.title} description={article.excerpt}><Breadcrumbs items={[{ label: "المقالات", href: "/blog/" }, { label: article.title }]} /><div className="content-card__meta"><time dateTime={date}>{new Intl.DateTimeFormat("ar-SA", { dateStyle: "long" }).format(new Date(date))}</time><span>حُدّث في <time dateTime={article.updated_at}>{new Intl.DateTimeFormat("ar-SA", { dateStyle: "long" }).format(new Date(article.updated_at))}</time></span><span>{article.reading_time_minutes} دقائق قراءة</span>{article.city ? <Link href={`/${article.city.slug}/`}>{article.city.name}</Link> : null}</div></PageHero><section className="content-section"><Container className="detail-layout"><article>{article.image ? <ResponsiveImage image={article.image} className="detail-media" sizes="(max-width: 960px) 100vw, 70vw" priority /> : null}<ArticleContent html={article.content} />{article.tags.length ? <div className="tag-list">{article.tags.map((tag) => <Link key={tag.id} href={tag.url}>#{tag.name}</Link>)}</div> : null}</article><aside className="detail-sidebar"><h2>عن المقال</h2>{article.category ? <p>التصنيف: <Link href={article.category.url}>{article.category.name}</Link></p> : null}{article.city ? <p>المدينة: <Link href={`/${article.city.slug}/`}>{article.city.name}</Link></p> : null}<h2>مشاركة المقال</h2><div className="share-links"><a href={`https://wa.me/?text=${shareText}%20${shareUrl}`} target="_blank" rel="noreferrer">واتساب</a><a href={`https://twitter.com/intent/tweet?text=${shareText}&url=${shareUrl}`} target="_blank" rel="noreferrer">منصة X</a></div><Link className="button" href="/quote-request/">استشارة المشروع</Link></aside></Container></section>{article.related_articles?.length ? <section className="content-section content-section--tinted"><Container><SectionHeading title="مقالات مرتبطة" /><div className="grid grid--3">{article.related_articles.map((item) => <ArticleCard key={item.id} article={item} />)}</div></Container></section> : null}<CallToAction /><JsonLd data={schema} /></>; }
