#!/usr/bin/env python3
"""Build the single public CSS bundle in deterministic source order."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = (
    "static/css/thmanyah.css",
    "static/css/style.css",
    "static/css/design-system-v2.css",
    "static/css/nakheel-najd-v3.css",
    "static/css/nakheel-najd-v4.css",
    "static/css/nakheel-najd-v4-1.css",
    "static/css/nakheel-najd-v4-2.css",
    "static/css/nakheel-najd-v4-3.css",
    "static/css/nakheel-najd-v4-4.css",
)
OUTPUT = ROOT / "static/css/site-v4-4.css"


def main() -> int:
    chunks = [
        "/* Generated by scripts/build_public_assets.py. Edit source files, not this bundle. */\n"
    ]
    for relative in SOURCES:
        source = ROOT / relative
        if not source.is_file():
            raise SystemExit(f"Missing CSS source: {relative}")
        chunks.append(f"\n/* ===== {relative} ===== */\n")
        chunks.append(source.read_text(encoding="utf-8-sig").rstrip())
        chunks.append("\n")
    OUTPUT.write_text("".join(chunks), encoding="utf-8")
    print(f"Built {OUTPUT.relative_to(ROOT)} from {len(SOURCES)} source files ({OUTPUT.stat().st_size} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
