# Generated by Django 4.2.7 on 2026-03-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_home_hero_background'),
        ('core', '0004_sitesettings_created_at'),
    ]

    operations = [
    ]
