# Generated by Django 4.2.7 on 2026-03-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_system_upgrade'),
        ('core', '0005_merge_20260323_0032'),
    ]

    operations = [
    ]
