# Generated by Django 4.2.7 on 2026-03-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_hero_background'),
        ('core', '0006_merge_20260323_0101'),
    ]

    operations = [
    ]
