# Generated by Django 5.2.17 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_homesection_homesectionmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="homepage_meta_description",
            field=models.TextField(default="تصميم وتنفيذ تنسيق الحدائق واللاندسكيب وزراعة ونقل النخيل وشبكات الري وصيانة المساحات الخارجية في مدن السعودية بخطة واضحة تناسب الموقع والمناخ."),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="homepage_meta_title",
            field=models.CharField(default="تنسيق حدائق ولاندسكيب وزراعة نخيل في السعودية | نخيل نجد", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="seo_default_keywords",
            field=models.CharField(blank=True, default="تنسيق حدائق, شركة تنسيق حدائق, لاندسكيب, تصميم حدائق منزلية, زراعة نخيل, نقل نخيل, شبكات ري, صيانة حدائق, السعودية", help_text="كلمات مفتاحية افتراضية مفصولة بفواصل.", max_length=500),
        ),
    ]
